### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BogdanJak** [mariinkys/BlazorServerTemplate#1]
Hi How its run?

I get error

![image](https://github.com/mariinkys/BlazorServerTemplate/assets/54505464/48e61c52-c8dd-450b-a9f4-a4bf9838504a)

**Comment by mariinkys** [comment]
This error happens because the field JWTKey in your BlszorServer appsettings.json is empty, you must fill this field with any random string between 15 and 40 characters, please note that a connection string to a database with the proper migration applied is also needed; with Visual Studio you can run ScriptDbContext in order to obtain a .sql that will create the default database structure for you.
